#!/bin/bash 
#
#PBS -N itest 
#PBS -j oe
#PBS -q s3par8c 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

COUNTER=1
STOP=1

while [  $COUNTER -le $STOP ]; do
      dir=$COUNTER
      mkdir $dir
      cp  ci* cavity.inp mat_SD.inp tdcis_* $dir/
      cd $dir/
      CALC=$COUNTER
      sed -i 's/NN/'"$CALC"'/g' *.inp
      #new=$RANDOM
      #sed -i 's/seed_to_change/'"$new"'/g' *.inp
      /s3_home/ecoccia/programs/WaveT.git/branches/input_namelist/embem.x_save < tdcis_nanoparticle_LF.inp > out 
      cd ../
      #echo Calculation done in $dir with SEED=$new >> iseed.dat
      let COUNTER=COUNTER+1
done


#cp multiple_script $PBS_O_WORKDIR
#cp *inp* script $PBS_O_WORKDIR 
#/opt/torque413/bin/pbsdsh $PBS_O_WORKDIR/multiple_script
