#!/bin/sh
#PBS -N LiCN_NP
#PBS -l nodes=1:ppn=12
#PBS -j oe
##PBS -W depend=afterany:74846

AMSHOME=/home/dantoni/DOTTORATO/versioni_AMS/versione_stabile_per_conti_di_LATEST_TRUNK/da_non_ricompilare/
ROOT=$PBS_O_WORKDIR

export AMSHOME
AMSBIN=$AMSHOME/bin
export AMSBIN
AMSRESOURCES=$AMSHOME/atomicdata
export AMSRESOURCES
SCMLICENSE=$AMSHOME/license.txt
export SCMLICENSE
PATH=$PATH:.:$AMSBIN
export PATH
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

set -x
date
#env

TMPDIR=/storage/biancorosso/scratch/$PBS_JOBID


mkdir $TMPDIR
cd $TMPDIR

AMS_RESULTSDIR=$TMPDIR
export AMS_RESULTSDIR
SCM_TMPDIR=$TMPDIR
export SCM_TMPDIR
export SCM_SHAR_NONUMA="no"
SCM_IOBUFFERSIZE=64
export SCM_IOBUFFERSIZE
SCM_VECTORLENGTH=64
export SCM_VECTORLENGTH


$AMSBIN/ams   << eor

Task SinglePoint


System
Atoms !Z-matrix
C   -0.136506 0.0 0.0
Li  -2.085506 0.0 0.0
N    1.010794 0.0 0.0
End
  Charge 0
End


Engine adf

  Relativity Level=None

  basis
    PerAtomType Symbol=C File=$AMSRESOURCES/ADF/TZP/C
    PerAtomType Symbol=Li File=$AMSRESOURCES/ADF/TZP/Li
    PerAtomType Symbol=N File=$AMSRESOURCES/ADF/TZP/N
  End

  Eprint
    eigval 1000 1000
    orbpoper -1000 1000
  End

  symmetry NOSYM

 
  XC 
    libxc CAM-B3LYP
  End

  SCF
   Converge 1.0E-08
  End
 
  Excitations
   davidson
     A 10
   End
   onlysing
   velocity
   KFWRITE 5
  End

PRINT DIPOLEMAT
SAVE TAPE15

EndEngine

eor


cat ams.log

mv adf.rkf $ROOT/TAPE21
mv TAPE15 $ROOT/TAPE15

cd ..
rm -fr $TMPDIR

ls -l
