#!/bin/sh
#SBATCH --export=ALL          #esporta le variabili
#SBATCH --job-name=sse_test
#SBATCH --nodes=1           #numero di nodi
#SBATCH --ntasks-per-node=4 #numero di processori per nodo (massimo 36)
#SBATCH --partition=ulow
# #SBATCH --nodelist=gn01,fn01,wn02,wn03,wn01,wn02,wn04,wn05,wn06,wn07


set -x
module purge
module load slurm #gcc-8.5.0/slurm-23.11.3 
module load intel-2024.2.0/intel_Comps-2024.2
module load intel-2024.2.0/intel_MPI-2024.2
module load intel-2024.2.0/intel_MKL-2024.2
#source /opt/share/comps/intel/oneapi/setvars.sh 

export OMP_NUM_THREADS=1
export I_MPI_FABRICS=shm:ofi
#export I_MPI_DEBUG=5
#date
#env

#EXE=/home/dallosto/codes/WaveT/WaveT/bin/WaveT-serial.x
ROOT=$SLURM_SUBMIT_DIR
#INP=$ROOT/inp.inp
#OUT=$ROOT/output
#

cd $ROOT
mpirun /home/sanchez/WaveT/WaveT/bin/WaveT-parallel.x < tdcis.inp > output
